# This is a basic workflow to help you get started with Actions

name: d
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
## jobs:
  # This workflow contains a single job called "build"
  ## build:
    # The type of runner that the job will run on
    ## runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    ## steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      ## - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      ## - name: Run a one-line script
      ##   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      ## - name: Run a multi-line script
       ##  run: |
       ##    echo Add other actions to build,
        ##   echo test, and deploy your project.
jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: yarn install, build
      run: |
        yarn
        yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }}
        BRANCH: master
        FOLDER: dist
        REPOSITORY_NAME: hefeng6500/hefeng6500.github.io
        TARGET_FOLDER: blog

      env:
        CI: true
